### ISSUE TITLE
Unable to initialize the delegate object in structure map 4.0.

### ISSUE THREAD

**Issue by ambadasrachha** [structuremap/structuremap#427]
In my class :

class RepositoryBase : IRepositoryCommon where TResultSet : ResultSet
{
public delegate AppServiceClient SerivceCleintFactory();
private readonly SerivceCleintFactory _serivceCleintFactory ;

RepositoryBase(serivceCleintFactory serivceCleintFactory )
{
_serivceCleintFactory = serivceCleintFactory 
}

"_serivceCleintFactory" object used for calling wcf service.
}
structure map 2.0 it's support following plugin assignment 
For.serivceCleintFactory) >().Use(() => new AppServiceClient());

But same plugin not working in structure map 4.0 registry class.

Please suggest on this

**Comment by jeremydmiller** [comment]
@ambadasrachha 

You might need to provide more information than that. I don't see anything that would not work in 4.0 in what you did there.

**Comment by ambadasrachha** [comment]
@jeremydmiller 
 
I am facing following compilation Errors - 

The type 'ServiceReference.AppServiceClient’ cannot be used as type parameter 'T' in the generic type or method 'StructureMap.Configuration.DSL.Expressions.CreatePluginFamilyExpression<TPluginType>.Use<T>(System.Linq.Expressions.Expression<System.Func<T>>)'. There is no implicit reference conversion from 'Enterprise.Web.ServiceReference.AppServiceClient’ to 'Enterprise.App.Web.Repository.Application.RepositoryBase<Enterprise.Model.Common.ResultSet>.AppServiceClientFactory

Actually we are migrating Structure map 2.0 to structure 4.0 and we made following changes in DI Registry class which is not supporting.

	We updated the Nugate Structure map 4.0 package 
	Changed namespace reference from using StructureMap.Configuration.DSL; to  using StructureMap; for implementing the following ApplicaotnRegistry and this ApplicationRegistry class which is actually used for DI hosting.
	AppServiceClient is my WCF Service Client object.

// Registry Classs
using StructureMap;

namespace Enterprise.App.Web.DependencyResolution
{
    public class ApplicationRegistry : Registry
    Public ApplicationRegistry()
   {

         //Issue with following mapping and this mapping works fine in previous version of structuremap 2.0 

      For<RepositoryBase<ResultSet>.ServiceClientFactory>().Use(() => new AppServiceClient());
      For<RepositoryBase<SummaryResultSet>.ServiceClientFactory>().Use(() => new    AppServiceClient());
    }
}

// Repository class 
public abstract class RepositoryBase<TResultSet> : IRepositoryCommon<TResultSet> where TResultSet : ResultSet
{

public delegate AppServiceClient ServiceClientFactory();        
private readonly ServiceClientFactory _serviceClientFactory;

protected RepositoryBase(ServiceClientFactory serviceClientFactory)
        {
            _serviceClientFactory= serviceClientFactory()
        }


//For actual service call
AppServiceClient apiServiceClient = _serviceClientFactory();
apiServiceClient.apimethod(“Test1”);

}

And Above Delegate base object we used in Derived Repository Class with same DI approach.

//Derived Repository class:
private readonly ServiceClientFactory _serviceClientFactory;

**Comment by jeremydmiller** [comment]
Can you try using the "Use(string description, Func<T>)" signature here? Are you sure that `AppServiceClient` can be cast to `RepositoryBase<ResultSet>.ServiceClientFactory`?

**Comment by ambadasrachha** [comment]
Yes I am Sure, With previous version of structure map registry class We doing the   
"AppServiceClient" cast to "RepositoryBase<ResultSet>.ServiceClientFactory"  and using this concept in multiple project.

As per your suggestion I tried all combination of "Use(string description, Func)" signature but facing same error.

Currently as a time constraint we are planing to go with structure map 3.1.6 as this version support previous functionality.

**Comment by ambadasrachha** [comment]
Hi @jeremydmiller 

We resolved this issue with by changing the usage of delegates to Func<> delegates(different flavor of traditional delegates). 

Looks like newer version expects Func<> delegates with Use() clause.

Old Code : 
Repository class :  
public delegate AppServiceClient ServiceClientFactory();
private readonly ServiceClientFactory _serviceClientFactory;

Registry class : 
For<RepositoryBase<ResultSet>.ServiceClientFactory>().Use(() => new AppServiceClient());
  For<RepositoryBase<SummaryResultSet>.ServiceClientFactory>().Use(() => new    AppServiceClient());

New Code :
Repository class :  
private readonly Func<IAppServiceClient>  _serviceClientFactory

Registry class : 
Func<IAppServiceClient> createContext = () => {return new AppServiceClient()} };
 For<Func<IAppServiceClient>>().Use(createContext);

-------------------------------------------------------------------------------------------------------------------------------
This solution is working for above my issue.!! Thanks for your guidance also ....

**Comment by ambadasrachha** [comment]
corrected the New code....
New Code :
Repository class :
private readonly Func<IAppServiceClient> _serviceClientFactory

Registry class : 
Func<IAppServiceClient> createContext = () => {return new AppServiceClient()} };
For>().Use(createContext);
